# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_game_1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Custom_Game_1(object):
    def setupUi(self, Custom_Game_1):
        Custom_Game_1.setObjectName("Custom_Game_1")
        Custom_Game_1.resize(660, 457)
        self.groupBox_6 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 60, 189, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Board_GBox = QtWidgets.QGroupBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Board_GBox.setFont(font)
        self.Board_GBox.setAlignment(QtCore.Qt.AlignCenter)
        self.Board_GBox.setFlat(False)
        self.Board_GBox.setObjectName("Board_GBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Board_GBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Board_8x8 = QtWidgets.QRadioButton(self.Board_GBox)
        self.Board_8x8.setChecked(True)
        self.Board_8x8.setObjectName("Board_8x8")
        self.verticalLayout_2.addWidget(self.Board_8x8)
        self.Board_9x9 = QtWidgets.QRadioButton(self.Board_GBox)
        self.Board_9x9.setObjectName("Board_9x9")
        self.verticalLayout_2.addWidget(self.Board_9x9)
        self.verticalLayout_3.addWidget(self.Board_GBox)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_3.addWidget(self.checkBox_4)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_15.setChecked(True)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout.addWidget(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout.addWidget(self.radioButton_17)
        self.verticalLayout_3.addWidget(self.groupBox_8)
        self.groupBox_7 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_7.setGeometry(QtCore.QRect(190, 60, 251, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 30, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 30, 71, 19))
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(130, 30, 61, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 90, 231, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setFlat(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.SL_GBox = QtWidgets.QGroupBox(self.groupBox_9)
        self.SL_GBox.setGeometry(QtCore.QRect(0, 30, 101, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SL_GBox.setFont(font)
        self.SL_GBox.setAlignment(QtCore.Qt.AlignCenter)
        self.SL_GBox.setFlat(False)
        self.SL_GBox.setObjectName("SL_GBox")
        self.SL_Default = QtWidgets.QRadioButton(self.SL_GBox)
        self.SL_Default.setGeometry(QtCore.QRect(10, 30, 81, 19))
        self.SL_Default.setChecked(True)
        self.SL_Default.setObjectName("SL_Default")
        self.SL_Mirror = QtWidgets.QRadioButton(self.SL_GBox)
        self.SL_Mirror.setGeometry(QtCore.QRect(10, 60, 71, 19))
        self.SL_Mirror.setObjectName("SL_Mirror")
        self.SL_Outpost = QtWidgets.QRadioButton(self.SL_GBox)
        self.SL_Outpost.setGeometry(QtCore.QRect(10, 90, 81, 19))
        self.SL_Outpost.setObjectName("SL_Outpost")
        self.CL_GBox = QtWidgets.QGroupBox(self.groupBox_9)
        self.CL_GBox.setEnabled(False)
        self.CL_GBox.setGeometry(QtCore.QRect(100, 30, 131, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CL_GBox.setFont(font)
        self.CL_GBox.setAlignment(QtCore.Qt.AlignCenter)
        self.CL_GBox.setFlat(False)
        self.CL_GBox.setObjectName("CL_GBox")
        self.CL_Default = QtWidgets.QRadioButton(self.CL_GBox)
        self.CL_Default.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.CL_Default.setChecked(True)
        self.CL_Default.setObjectName("CL_Default")
        self.CL_QDown = QtWidgets.QRadioButton(self.CL_GBox)
        self.CL_QDown.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.CL_QDown.setObjectName("CL_QDown")
        self.CL_RKnight = QtWidgets.QRadioButton(self.CL_GBox)
        self.CL_RKnight.setGeometry(QtCore.QRect(10, 90, 121, 19))
        self.CL_RKnight.setObjectName("CL_RKnight")
        self.label = QtWidgets.QLabel(Custom_Game_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Custom_Game_1)
        self.pushButton.setGeometry(QtCore.QRect(450, 360, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Custom_Game_1)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 320, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.Timer_GBox = QtWidgets.QGroupBox(Custom_Game_1)
        self.Timer_GBox.setGeometry(QtCore.QRect(200, 320, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Timer_GBox.setFont(font)
        self.Timer_GBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Timer_GBox.setFlat(False)
        self.Timer_GBox.setCheckable(True)
        self.Timer_GBox.setObjectName("Timer_GBox")
        self.checkBox_3 = QtWidgets.QCheckBox(self.Timer_GBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 70, 61, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtWidgets.QCheckBox(self.Timer_GBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 100, 91, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.Timer_GBox)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 40, 101, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.timeEdit = QtWidgets.QTimeEdit(self.Timer_GBox)
        self.timeEdit.setGeometry(QtCore.QRect(120, 0, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.Timer_GBox)
        self.timeEdit_2.setGeometry(QtCore.QRect(120, 40, 118, 22))
        self.timeEdit_2.setFrame(True)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.Timer_GBox)
        self.timeEdit_3.setGeometry(QtCore.QRect(120, 70, 118, 22))
        self.timeEdit_3.setFrame(True)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.Timer_GBox)
        self.timeEdit_4.setGeometry(QtCore.QRect(120, 100, 118, 22))
        self.timeEdit_4.setFrame(True)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.groupBox_5 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_5.setGeometry(QtCore.QRect(440, 60, 211, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineup_preview = QtWidgets.QLabel(self.groupBox_5)
        self.lineup_preview.setGeometry(QtCore.QRect(10, 40, 191, 191))
        self.lineup_preview.setText("")
        self.lineup_preview.setPixmap(QtGui.QPixmap("../resources/board_minimal.png"))
        self.lineup_preview.setScaledContents(True)
        self.lineup_preview.setObjectName("lineup_preview")

        self.retranslateUi(Custom_Game_1)
        self.Board_8x8.clicked['bool'].connect(self.CL_GBox.setDisabled)
        self.Board_8x8.clicked['bool'].connect(self.CL_Default.setChecked)
        self.Board_9x9.clicked['bool'].connect(self.SL_Default.setChecked)
        self.Board_9x9.clicked['bool'].connect(self.SL_GBox.setDisabled)
        self.Board_8x8.clicked['bool'].connect(self.SL_GBox.setEnabled)
        self.Board_9x9.clicked['bool'].connect(self.CL_GBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Custom_Game_1)

    def retranslateUi(self, Custom_Game_1):
        _translate = QtCore.QCoreApplication.translate
        Custom_Game_1.setWindowTitle(_translate("Custom_Game_1", "Form"))
        self.groupBox_6.setTitle(_translate("Custom_Game_1", "Game Options"))
        self.Board_GBox.setTitle(_translate("Custom_Game_1", "Board Selection"))
        self.Board_8x8.setText(_translate("Custom_Game_1", "Chess [ 8x8 ]"))
        self.Board_9x9.setText(_translate("Custom_Game_1", "Shogi [ 9x9 ]"))
        self.checkBox.setText(_translate("Custom_Game_1", "Promoted Drop"))
        self.checkBox_2.setText(_translate("Custom_Game_1", "Metal Piece\n"
"en-passant"))
        self.checkBox_4.setText(_translate("Custom_Game_1", "Metal Piece\n"
"Double initial move"))
        self.groupBox_8.setTitle(_translate("Custom_Game_1", "Capture Mode"))
        self.radioButton_15.setText(_translate("Custom_Game_1", "Crazyhouse"))
        self.radioButton_16.setText(_translate("Custom_Game_1", "Graveyard"))
        self.radioButton_17.setText(_translate("Custom_Game_1", "Shogi Pieces Only"))
        self.groupBox_7.setTitle(_translate("Custom_Game_1", "Player Options"))
        self.groupBox_4.setTitle(_translate("Custom_Game_1", "Player 1 Side"))
        self.radioButton_7.setText(_translate("Custom_Game_1", "Chess"))
        self.radioButton_8.setText(_translate("Custom_Game_1", "Shogi"))
        self.groupBox_9.setTitle(_translate("Custom_Game_1", "Lineup"))
        self.SL_GBox.setTitle(_translate("Custom_Game_1", "Shogi"))
        self.SL_Default.setText(_translate("Custom_Game_1", "Default"))
        self.SL_Mirror.setText(_translate("Custom_Game_1", "Mirror"))
        self.SL_Outpost.setText(_translate("Custom_Game_1", "Outpost"))
        self.CL_GBox.setTitle(_translate("Custom_Game_1", " Chess"))
        self.CL_Default.setText(_translate("Custom_Game_1", "Default"))
        self.CL_QDown.setText(_translate("Custom_Game_1", "Queen Down"))
        self.CL_RKnight.setText(_translate("Custom_Game_1", "Royal Knight"))
        self.label.setText(_translate("Custom_Game_1", "Versus Mode"))
        self.pushButton.setText(_translate("Custom_Game_1", "Start Playing"))
        self.pushButton_2.setText(_translate("Custom_Game_1", "Advanced Options"))
        self.Timer_GBox.setTitle(_translate("Custom_Game_1", "Timer"))
        self.checkBox_3.setText(_translate("Custom_Game_1", "Delay"))
        self.checkBox_5.setText(_translate("Custom_Game_1", "Byoyomi"))
        self.checkBox_6.setText(_translate("Custom_Game_1", "Increment"))
        self.groupBox_5.setTitle(_translate("Custom_Game_1", "Lineup Preview"))

