# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_game_1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Custom_Game_1(object):
    def setupUi(self, Custom_Game_1):
        Custom_Game_1.setObjectName("Custom_Game_1")
        Custom_Game_1.resize(658, 458)
        self.groupBox_6 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 60, 181, 391))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setGeometry(QtCore.QRect(20, 30, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox.setGeometry(QtCore.QRect(20, 130, 131, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 160, 111, 41))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 210, 161, 41))
        self.checkBox_4.setObjectName("checkBox_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 260, 161, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_15.setChecked(True)
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_16.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_17.setGeometry(QtCore.QRect(10, 90, 151, 21))
        self.radioButton_17.setObjectName("radioButton_17")
        self.groupBox_7 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_7.setGeometry(QtCore.QRect(190, 60, 251, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 30, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 30, 71, 19))
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(130, 30, 61, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 90, 231, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setFlat(False)
        self.groupBox_9.setObjectName("groupBox_9")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 30, 101, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 30, 81, 19))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 60, 71, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 90, 81, 19))
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_9)
        self.groupBox_2.setGeometry(QtCore.QRect(100, 30, 131, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 90, 121, 19))
        self.radioButton_11.setObjectName("radioButton_11")
        self.label = QtWidgets.QLabel(Custom_Game_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Custom_Game_1)
        self.pushButton.setGeometry(QtCore.QRect(450, 360, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Custom_Game_1)
        self.pushButton_2.setGeometry(QtCore.QRect(450, 320, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_10 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_10.setGeometry(QtCore.QRect(200, 320, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setCheckable(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 70, 61, 19))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 100, 91, 19))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_10)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 40, 101, 19))
        self.checkBox_6.setObjectName("checkBox_6")
        self.timeEdit = QtWidgets.QTimeEdit(self.groupBox_10)
        self.timeEdit.setGeometry(QtCore.QRect(120, 0, 118, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.timeEdit_2 = QtWidgets.QTimeEdit(self.groupBox_10)
        self.timeEdit_2.setGeometry(QtCore.QRect(120, 40, 118, 22))
        self.timeEdit_2.setFrame(True)
        self.timeEdit_2.setObjectName("timeEdit_2")
        self.timeEdit_3 = QtWidgets.QTimeEdit(self.groupBox_10)
        self.timeEdit_3.setGeometry(QtCore.QRect(120, 70, 118, 22))
        self.timeEdit_3.setFrame(True)
        self.timeEdit_3.setObjectName("timeEdit_3")
        self.timeEdit_4 = QtWidgets.QTimeEdit(self.groupBox_10)
        self.timeEdit_4.setGeometry(QtCore.QRect(120, 100, 118, 22))
        self.timeEdit_4.setFrame(True)
        self.timeEdit_4.setObjectName("timeEdit_4")
        self.groupBox_5 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_5.setGeometry(QtCore.QRect(440, 60, 211, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineup_preview = QtWidgets.QLabel(self.groupBox_5)
        self.lineup_preview.setGeometry(QtCore.QRect(10, 40, 191, 191))
        self.lineup_preview.setText("")
        self.lineup_preview.setPixmap(QtGui.QPixmap("../resources/board_minimal.png"))
        self.lineup_preview.setScaledContents(True)
        self.lineup_preview.setObjectName("lineup_preview")

        self.retranslateUi(Custom_Game_1)
        QtCore.QMetaObject.connectSlotsByName(Custom_Game_1)

    def retranslateUi(self, Custom_Game_1):
        _translate = QtCore.QCoreApplication.translate
        Custom_Game_1.setWindowTitle(_translate("Custom_Game_1", "Form"))
        self.groupBox_6.setTitle(_translate("Custom_Game_1", "Game Options"))
        self.groupBox.setTitle(_translate("Custom_Game_1", "Board Selection"))
        self.radioButton.setText(_translate("Custom_Game_1", "Chess [ 8x8 ]"))
        self.radioButton_2.setText(_translate("Custom_Game_1", "Shogi [ 9x9 ]"))
        self.checkBox.setText(_translate("Custom_Game_1", "Promoted Drop"))
        self.checkBox_2.setText(_translate("Custom_Game_1", "Metal Piece\n"
"en-passant"))
        self.checkBox_4.setText(_translate("Custom_Game_1", "Metal Piece\n"
"Double initial move"))
        self.groupBox_8.setTitle(_translate("Custom_Game_1", "Capture Mode"))
        self.radioButton_15.setText(_translate("Custom_Game_1", "Crazyhouse"))
        self.radioButton_16.setText(_translate("Custom_Game_1", "Graveyard"))
        self.radioButton_17.setText(_translate("Custom_Game_1", "Shogi Pieces Only"))
        self.groupBox_7.setTitle(_translate("Custom_Game_1", "Player Options"))
        self.groupBox_4.setTitle(_translate("Custom_Game_1", "Player 1 Side"))
        self.radioButton_7.setText(_translate("Custom_Game_1", "Chess"))
        self.radioButton_8.setText(_translate("Custom_Game_1", "Shogi"))
        self.groupBox_9.setTitle(_translate("Custom_Game_1", "Lineup"))
        self.groupBox_3.setTitle(_translate("Custom_Game_1", "Shogi"))
        self.radioButton_5.setText(_translate("Custom_Game_1", "Default"))
        self.radioButton_6.setText(_translate("Custom_Game_1", "Mirror"))
        self.radioButton_12.setText(_translate("Custom_Game_1", "Outpost"))
        self.groupBox_2.setTitle(_translate("Custom_Game_1", " Chess"))
        self.radioButton_3.setText(_translate("Custom_Game_1", "Default"))
        self.radioButton_4.setText(_translate("Custom_Game_1", "Queen Down"))
        self.radioButton_11.setText(_translate("Custom_Game_1", "Royal Knight"))
        self.label.setText(_translate("Custom_Game_1", "Versus Mode"))
        self.pushButton.setText(_translate("Custom_Game_1", "Start Playing"))
        self.pushButton_2.setText(_translate("Custom_Game_1", "Advanced Options"))
        self.groupBox_10.setTitle(_translate("Custom_Game_1", "Timer"))
        self.checkBox_3.setText(_translate("Custom_Game_1", "Delay"))
        self.checkBox_5.setText(_translate("Custom_Game_1", "Byoyomi"))
        self.checkBox_6.setText(_translate("Custom_Game_1", "Increment"))
        self.groupBox_5.setTitle(_translate("Custom_Game_1", "Lineup Preview"))

