# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'custom_game_1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Custom_Game_1(object):
    def setupUi(self, Custom_Game_1):
        Custom_Game_1.setObjectName("Custom_Game_1")
        Custom_Game_1.resize(660, 457)
        Custom_Game_1.setMinimumSize(QtCore.QSize(660, 457))
        Custom_Game_1.setMaximumSize(QtCore.QSize(660, 457))
        self.GrpGameOpts = QtWidgets.QGroupBox(Custom_Game_1)
        self.GrpGameOpts.setGeometry(QtCore.QRect(10, 60, 189, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GrpGameOpts.setFont(font)
        self.GrpGameOpts.setAlignment(QtCore.Qt.AlignCenter)
        self.GrpGameOpts.setFlat(False)
        self.GrpGameOpts.setObjectName("GrpGameOpts")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.GrpGameOpts)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BoardOpts = QtWidgets.QGroupBox(self.GrpGameOpts)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BoardOpts.setFont(font)
        self.BoardOpts.setAlignment(QtCore.Qt.AlignCenter)
        self.BoardOpts.setFlat(False)
        self.BoardOpts.setObjectName("BoardOpts")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.BoardOpts)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Board_8x8 = QtWidgets.QRadioButton(self.BoardOpts)
        self.Board_8x8.setChecked(True)
        self.Board_8x8.setObjectName("Board_8x8")
        self.verticalLayout_2.addWidget(self.Board_8x8)
        self.Board_9x9 = QtWidgets.QRadioButton(self.BoardOpts)
        self.Board_9x9.setObjectName("Board_9x9")
        self.verticalLayout_2.addWidget(self.Board_9x9)
        self.verticalLayout_3.addWidget(self.BoardOpts)
        self.e_promodrop = QtWidgets.QCheckBox(self.GrpGameOpts)
        self.e_promodrop.setObjectName("e_promodrop")
        self.verticalLayout_3.addWidget(self.e_promodrop)
        self.e_menpassant = QtWidgets.QCheckBox(self.GrpGameOpts)
        self.e_menpassant.setChecked(True)
        self.e_menpassant.setObjectName("e_menpassant")
        self.verticalLayout_3.addWidget(self.e_menpassant)
        self.e_mdoublemove = QtWidgets.QCheckBox(self.GrpGameOpts)
        self.e_mdoublemove.setObjectName("e_mdoublemove")
        self.verticalLayout_3.addWidget(self.e_mdoublemove)
        self.CaptureOpts = QtWidgets.QGroupBox(self.GrpGameOpts)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CaptureOpts.setFont(font)
        self.CaptureOpts.setAlignment(QtCore.Qt.AlignCenter)
        self.CaptureOpts.setFlat(False)
        self.CaptureOpts.setObjectName("CaptureOpts")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.CaptureOpts)
        self.verticalLayout.setObjectName("verticalLayout")
        self.c_crazyhouse = QtWidgets.QRadioButton(self.CaptureOpts)
        self.c_crazyhouse.setChecked(True)
        self.c_crazyhouse.setObjectName("c_crazyhouse")
        self.verticalLayout.addWidget(self.c_crazyhouse)
        self.c_graveyard = QtWidgets.QRadioButton(self.CaptureOpts)
        self.c_graveyard.setObjectName("c_graveyard")
        self.verticalLayout.addWidget(self.c_graveyard)
        self.c_shogionly = QtWidgets.QRadioButton(self.CaptureOpts)
        self.c_shogionly.setObjectName("c_shogionly")
        self.verticalLayout.addWidget(self.c_shogionly)
        self.verticalLayout_3.addWidget(self.CaptureOpts)
        self.GrpPlayerOpts = QtWidgets.QGroupBox(Custom_Game_1)
        self.GrpPlayerOpts.setGeometry(QtCore.QRect(190, 60, 251, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GrpPlayerOpts.setFont(font)
        self.GrpPlayerOpts.setAlignment(QtCore.Qt.AlignCenter)
        self.GrpPlayerOpts.setFlat(False)
        self.GrpPlayerOpts.setObjectName("GrpPlayerOpts")
        self.P1Side = QtWidgets.QGroupBox(self.GrpPlayerOpts)
        self.P1Side.setGeometry(QtCore.QRect(10, 30, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.P1Side.setFont(font)
        self.P1Side.setAlignment(QtCore.Qt.AlignCenter)
        self.P1Side.setFlat(False)
        self.P1Side.setObjectName("P1Side")
        self.P1_Chess = QtWidgets.QRadioButton(self.P1Side)
        self.P1_Chess.setGeometry(QtCore.QRect(10, 30, 71, 19))
        self.P1_Chess.setChecked(True)
        self.P1_Chess.setObjectName("P1_Chess")
        self.P1_Shogi = QtWidgets.QRadioButton(self.P1Side)
        self.P1_Shogi.setGeometry(QtCore.QRect(130, 30, 61, 19))
        self.P1_Shogi.setObjectName("P1_Shogi")
        self.Lineup = QtWidgets.QGroupBox(self.GrpPlayerOpts)
        self.Lineup.setGeometry(QtCore.QRect(10, 90, 231, 151))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Lineup.setFont(font)
        self.Lineup.setAlignment(QtCore.Qt.AlignCenter)
        self.Lineup.setFlat(False)
        self.Lineup.setObjectName("Lineup")
        self.L_Shogi = QtWidgets.QGroupBox(self.Lineup)
        self.L_Shogi.setGeometry(QtCore.QRect(0, 30, 101, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_Shogi.setFont(font)
        self.L_Shogi.setAlignment(QtCore.Qt.AlignCenter)
        self.L_Shogi.setFlat(False)
        self.L_Shogi.setObjectName("L_Shogi")
        self.SL_Default = QtWidgets.QRadioButton(self.L_Shogi)
        self.SL_Default.setGeometry(QtCore.QRect(10, 30, 81, 19))
        self.SL_Default.setChecked(True)
        self.SL_Default.setObjectName("SL_Default")
        self.SL_Mirror = QtWidgets.QRadioButton(self.L_Shogi)
        self.SL_Mirror.setGeometry(QtCore.QRect(10, 60, 71, 19))
        self.SL_Mirror.setObjectName("SL_Mirror")
        self.SL_Outpost = QtWidgets.QRadioButton(self.L_Shogi)
        self.SL_Outpost.setGeometry(QtCore.QRect(10, 90, 81, 19))
        self.SL_Outpost.setObjectName("SL_Outpost")
        self.L_Chess = QtWidgets.QGroupBox(self.Lineup)
        self.L_Chess.setEnabled(False)
        self.L_Chess.setGeometry(QtCore.QRect(100, 30, 131, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.L_Chess.setFont(font)
        self.L_Chess.setAlignment(QtCore.Qt.AlignCenter)
        self.L_Chess.setFlat(False)
        self.L_Chess.setObjectName("L_Chess")
        self.CL_Default = QtWidgets.QRadioButton(self.L_Chess)
        self.CL_Default.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.CL_Default.setChecked(True)
        self.CL_Default.setObjectName("CL_Default")
        self.CL_QDown = QtWidgets.QRadioButton(self.L_Chess)
        self.CL_QDown.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.CL_QDown.setObjectName("CL_QDown")
        self.CL_RKnight = QtWidgets.QRadioButton(self.L_Chess)
        self.CL_RKnight.setGeometry(QtCore.QRect(10, 90, 121, 19))
        self.CL_RKnight.setObjectName("CL_RKnight")
        self.label = QtWidgets.QLabel(Custom_Game_1)
        self.label.setGeometry(QtCore.QRect(10, 10, 641, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.buttonStart = QtWidgets.QPushButton(Custom_Game_1)
        self.buttonStart.setGeometry(QtCore.QRect(450, 360, 201, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.buttonStart.setFont(font)
        self.buttonStart.setObjectName("buttonStart")
        self.buttonAdvOpts = QtWidgets.QPushButton(Custom_Game_1)
        self.buttonAdvOpts.setGeometry(QtCore.QRect(450, 320, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.buttonAdvOpts.setFont(font)
        self.buttonAdvOpts.setObjectName("buttonAdvOpts")
        self.GrpTimerOpts = QtWidgets.QGroupBox(Custom_Game_1)
        self.GrpTimerOpts.setGeometry(QtCore.QRect(200, 320, 241, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.GrpTimerOpts.setFont(font)
        self.GrpTimerOpts.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.GrpTimerOpts.setFlat(False)
        self.GrpTimerOpts.setCheckable(True)
        self.GrpTimerOpts.setObjectName("GrpTimerOpts")
        self.checkDelay = QtWidgets.QCheckBox(self.GrpTimerOpts)
        self.checkDelay.setGeometry(QtCore.QRect(10, 70, 61, 19))
        self.checkDelay.setObjectName("checkDelay")
        self.checkByoyomi = QtWidgets.QCheckBox(self.GrpTimerOpts)
        self.checkByoyomi.setGeometry(QtCore.QRect(10, 100, 91, 19))
        self.checkByoyomi.setObjectName("checkByoyomi")
        self.checkIncrement = QtWidgets.QCheckBox(self.GrpTimerOpts)
        self.checkIncrement.setGeometry(QtCore.QRect(10, 40, 101, 19))
        self.checkIncrement.setObjectName("checkIncrement")
        self.timeTimer = QtWidgets.QTimeEdit(self.GrpTimerOpts)
        self.timeTimer.setGeometry(QtCore.QRect(120, 0, 118, 22))
        self.timeTimer.setObjectName("timeTimer")
        self.timeIncrement = QtWidgets.QTimeEdit(self.GrpTimerOpts)
        self.timeIncrement.setGeometry(QtCore.QRect(120, 40, 118, 22))
        self.timeIncrement.setFrame(True)
        self.timeIncrement.setObjectName("timeIncrement")
        self.timeDelay = QtWidgets.QTimeEdit(self.GrpTimerOpts)
        self.timeDelay.setGeometry(QtCore.QRect(120, 70, 118, 22))
        self.timeDelay.setFrame(True)
        self.timeDelay.setObjectName("timeDelay")
        self.timeByoyomi = QtWidgets.QTimeEdit(self.GrpTimerOpts)
        self.timeByoyomi.setGeometry(QtCore.QRect(120, 100, 118, 22))
        self.timeByoyomi.setFrame(True)
        self.timeByoyomi.setObjectName("timeByoyomi")
        self.groupBox_5 = QtWidgets.QGroupBox(Custom_Game_1)
        self.groupBox_5.setGeometry(QtCore.QRect(440, 60, 211, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineup_preview = QtWidgets.QLabel(self.groupBox_5)
        self.lineup_preview.setGeometry(QtCore.QRect(10, 40, 191, 191))
        self.lineup_preview.setText("")
        self.lineup_preview.setPixmap(QtGui.QPixmap("../resources/board_minimal.png"))
        self.lineup_preview.setScaledContents(True)
        self.lineup_preview.setObjectName("lineup_preview")

        self.retranslateUi(Custom_Game_1)
        self.Board_8x8.clicked['bool'].connect(self.L_Chess.setDisabled)
        self.Board_8x8.clicked['bool'].connect(self.CL_Default.setChecked)
        self.Board_9x9.clicked['bool'].connect(self.SL_Default.setChecked)
        self.Board_9x9.clicked['bool'].connect(self.L_Shogi.setDisabled)
        self.Board_8x8.clicked['bool'].connect(self.L_Shogi.setEnabled)
        self.Board_9x9.clicked['bool'].connect(self.L_Chess.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Custom_Game_1)

    def retranslateUi(self, Custom_Game_1):
        _translate = QtCore.QCoreApplication.translate
        Custom_Game_1.setWindowTitle(_translate("Custom_Game_1", "Form"))
        self.GrpGameOpts.setTitle(_translate("Custom_Game_1", "Game Options"))
        self.BoardOpts.setTitle(_translate("Custom_Game_1", "Board Selection"))
        self.Board_8x8.setText(_translate("Custom_Game_1", "Chess [ 8x8 ]"))
        self.Board_9x9.setText(_translate("Custom_Game_1", "Shogi [ 9x9 ]"))
        self.e_promodrop.setText(_translate("Custom_Game_1", "Promoted Drop"))
        self.e_menpassant.setText(_translate("Custom_Game_1", "Metal Piece\n"
"en-passant"))
        self.e_mdoublemove.setText(_translate("Custom_Game_1", "Metal Piece\n"
"Double initial move"))
        self.CaptureOpts.setTitle(_translate("Custom_Game_1", "Capture Mode"))
        self.c_crazyhouse.setText(_translate("Custom_Game_1", "Crazyhouse"))
        self.c_graveyard.setText(_translate("Custom_Game_1", "Graveyard"))
        self.c_shogionly.setText(_translate("Custom_Game_1", "Shogi Pieces Only"))
        self.GrpPlayerOpts.setTitle(_translate("Custom_Game_1", "Player Options"))
        self.P1Side.setTitle(_translate("Custom_Game_1", "Player 1 Side"))
        self.P1_Chess.setText(_translate("Custom_Game_1", "Chess"))
        self.P1_Shogi.setText(_translate("Custom_Game_1", "Shogi"))
        self.Lineup.setTitle(_translate("Custom_Game_1", "Lineup"))
        self.L_Shogi.setTitle(_translate("Custom_Game_1", "Shogi"))
        self.SL_Default.setText(_translate("Custom_Game_1", "Default"))
        self.SL_Mirror.setText(_translate("Custom_Game_1", "Mirror"))
        self.SL_Outpost.setText(_translate("Custom_Game_1", "Outpost"))
        self.L_Chess.setTitle(_translate("Custom_Game_1", " Chess"))
        self.CL_Default.setText(_translate("Custom_Game_1", "Default"))
        self.CL_QDown.setText(_translate("Custom_Game_1", "Queen Down"))
        self.CL_RKnight.setText(_translate("Custom_Game_1", "Royal Knight"))
        self.label.setText(_translate("Custom_Game_1", "Versus Mode"))
        self.buttonStart.setText(_translate("Custom_Game_1", "Start Playing"))
        self.buttonAdvOpts.setText(_translate("Custom_Game_1", "Advanced Options"))
        self.GrpTimerOpts.setTitle(_translate("Custom_Game_1", "Timer"))
        self.checkDelay.setText(_translate("Custom_Game_1", "Delay"))
        self.checkByoyomi.setText(_translate("Custom_Game_1", "Byoyomi"))
        self.checkIncrement.setText(_translate("Custom_Game_1", "Increment"))
        self.groupBox_5.setTitle(_translate("Custom_Game_1", "Lineup Preview"))
