# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form2.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 470)
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 60, 181, 401))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setGeometry(QtCore.QRect(20, 40, 141, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox.setGeometry(QtCore.QRect(20, 140, 131, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 170, 111, 41))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 220, 161, 41))
        self.checkBox_4.setObjectName("checkBox_4")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 270, 161, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setFlat(False)
        self.groupBox_8.setObjectName("groupBox_8")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_15.setChecked(True)
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_16.setGeometry(QtCore.QRect(10, 60, 141, 21))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_8)
        self.radioButton_17.setGeometry(QtCore.QRect(10, 90, 151, 21))
        self.radioButton_17.setObjectName("radioButton_17")
        self.groupBox_7 = QtWidgets.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(190, 60, 351, 291))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 50, 161, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_7.setChecked(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 100, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 90, 121, 19))
        self.radioButton_11.setObjectName("radioButton_11")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_5.setGeometry(QtCore.QRect(180, 50, 161, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setFlat(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_9.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_9.setChecked(False)
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox_5)
        self.radioButton_10.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 100, 161, 131))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 30, 121, 19))
        self.radioButton_5.setChecked(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 60, 121, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 90, 121, 19))
        self.radioButton_12.setObjectName("radioButton_12")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(370, 360, 171, 101))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 410, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(200, 360, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_6.setTitle(_translate("Form", "Game Options"))
        self.groupBox.setTitle(_translate("Form", "Board Selection"))
        self.radioButton.setText(_translate("Form", "Chess [ 8x8 ]"))
        self.radioButton_2.setText(_translate("Form", "Shogi [ 9x9 ]"))
        self.checkBox.setText(_translate("Form", "Promoted Drop"))
        self.checkBox_2.setText(_translate("Form", "Metal Piece\n"
"en-passant"))
        self.checkBox_4.setText(_translate("Form", "Metal Piece\n"
"Double initial move"))
        self.groupBox_8.setTitle(_translate("Form", "Capture Mode"))
        self.radioButton_15.setText(_translate("Form", "Crazyhouse"))
        self.radioButton_16.setText(_translate("Form", "Graveyard"))
        self.radioButton_17.setText(_translate("Form", "Shogi Pieces Only"))
        self.groupBox_7.setTitle(_translate("Form", "Player Options"))
        self.groupBox_4.setTitle(_translate("Form", "Player 1"))
        self.radioButton_7.setText(_translate("Form", "Chess"))
        self.radioButton_8.setText(_translate("Form", "Shogi"))
        self.groupBox_2.setTitle(_translate("Form", "Lineup - Player 1"))
        self.radioButton_3.setText(_translate("Form", "Default"))
        self.radioButton_4.setText(_translate("Form", "Queen Down"))
        self.radioButton_11.setText(_translate("Form", "Royal Knight"))
        self.groupBox_5.setTitle(_translate("Form", "Player 2"))
        self.radioButton_9.setText(_translate("Form", "Chess"))
        self.radioButton_10.setText(_translate("Form", "Shogi"))
        self.groupBox_3.setTitle(_translate("Form", "Lineup - Player 2"))
        self.radioButton_5.setText(_translate("Form", "Default"))
        self.radioButton_6.setText(_translate("Form", "Mirror"))
        self.radioButton_12.setText(_translate("Form", "Outpost"))
        self.label.setText(_translate("Form", "Versus Mode"))
        self.pushButton.setText(_translate("Form", "Start Playing"))
        self.pushButton_2.setText(_translate("Form", "Advanced..."))
        self.pushButton_3.setText(_translate("Form", "Timer Controls"))
