import chessVshogi.pieces as pieces

Piece_Resource_Corresp = {
    "C_WP": ":/Chess/resources/chess_48/Chess_plt48.png",
    "C_WR": ":/Chess/resources/chess_48/Chess_rlt48.png",
    "C_WN": ":/Chess/resources/chess_48/Chess_nlt48.png",
    "C_WB": ":/Chess/resources/chess_48/Chess_blt48.png",
    "C_WQ": ":/Chess/resources/chess_48/Chess_qlt48.png",
    "C_WK": ":/Chess/resources/chess_48/Chess_klt48.png",
    "C_BP": ":/Chess/resources/chess_48/Chess_pdt48.png",
    "C_BR": ":/Chess/resources/chess_48/Chess_rdt48.png",
    "C_BN": ":/Chess/resources/chess_48/Chess_ndt48.png",
    "C_BB": ":/Chess/resources/chess_48/Chess_bdt48.png",
    "C_BQ": ":/Chess/resources/chess_48/Chess_qdt48.png",
    "C_BK": ":/Chess/resources/chess_48/Chess_kdt48.png",
    "S_BP": ":/Ichiji/resources/Ichiji/Gfu.png",
    "S_BL": ":/Ichiji/resources/Ichiji/Gkyo.png",
    "S_BN": ":/Ichiji/resources/Ichiji/Gkei.png",
    "S_BS": ":/Ichiji/resources/Ichiji/Ggin.png",
    "S_BG": ":/Ichiji/resources/Ichiji/Gkin.png",
    "S_BK": ":/Ichiji/resources/Ichiji/Ggyoku.png",
    "S_BB": ":/Ichiji/resources/Ichiji/Gkaku.png",
    "S_BR": ":/Ichiji/resources/Ichiji/Ghi.png",
    "S_WP": ":/Ichiji/resources/Ichiji/Sfu.png",
    "S_WL": ":/Ichiji/resources/Ichiji/Skyo.png",
    "S_WN": ":/Ichiji/resources/Ichiji/Skei.png",
    "S_WS": ":/Ichiji/resources/Ichiji/Sgin.png",
    "S_WG": ":/Ichiji/resources/Ichiji/Skin.png",
    "S_WK": ":/Ichiji/resources/Ichiji/Sou.png",
    "S_WB": ":/Ichiji/resources/Ichiji/Skaku.png",
    "S_WR": ":/Ichiji/resources/Ichiji/Shi.png",
}

Piece_Class_Corresp = {
    "C_WP": pieces.WhitePawn,
    "C_WR": pieces.Rook,
    "C_WN": pieces.Knight,
    "C_WB": pieces.Bishop,
    "C_WQ": pieces.Queen,
    "C_WK": pieces.King,
    "C_BP": pieces.BlackPawn,
    "C_BR": pieces.Rook,
    "C_BN": pieces.Knight,
    "C_BB": pieces.Bishop,
    "C_BQ": pieces.Queen,
    "C_BK": pieces.King,
    "S_BP": "",
    "S_BL": "",
    "S_BN": "",
    "S_BS": "",
    "S_BG": "",
    "S_BK": "",
    "S_BB": "",
    "S_BR": "",
    "S_WP": "",
    "S_WL": "",
    "S_WN": "",
    "S_WS": "",
    "S_WG": "",
    "S_WK": "",
    "S_WB": "",
    "S_WR": ""
}