import chessVshogi.pieces as pieces

mapper = {"C_WP": {"resource": ":/Chess/resources/chess_48/Chess_plt48.png",
                   "piece": pieces.Pawn},
          "C_WR": {"resource": ":/Chess/resources/chess_48/Chess_rlt48.png",
                   "piece": pieces.Rook},
          "C_WN": {"resource": ":/Chess/resources/chess_48/Chess_nlt48.png",
                   "piece": pieces.Knight},
          "C_WB": {"resource": ":/Chess/resources/chess_48/Chess_blt48.png",
                   "piece": pieces.Bishop},
          "C_WQ": {"resource": ":/Chess/resources/chess_48/Chess_qlt48.png",
                   "piece": pieces.Queen},
          "C_WK": {"resource": ":/Chess/resources/chess_48/Chess_klt48.png",
                   "piece": pieces.King},
          "C_BP": {"resource": ":/Chess/resources/chess_48/Chess_pdt48.png",
                   "piece": pieces.Pawn},
          "C_BR": {"resource": ":/Chess/resources/chess_48/Chess_rdt48.png",
                   "piece": pieces.Rook},
          "C_BN": {"resource": ":/Chess/resources/chess_48/Chess_ndt48.png",
                   "piece": pieces.Knight},
          "C_BB": {"resource": ":/Chess/resources/chess_48/Chess_bdt48.png",
                   "piece": pieces.Bishop},
          "C_BQ": {"resource": ":/Chess/resources/chess_48/Chess_qdt48.png",
                   "piece": pieces.Queen},
          "C_BK": {"resource": ":/Chess/resources/chess_48/Chess_kdt48.png",
                   "piece": pieces.King},
          "S_BP": {"resource": ":/Ichiji/resources/Ichiji/Gfu.png",
                   "piece": pieces.S_Pawn},
          "S_BL": {"resource": ":/Ichiji/resources/Ichiji/Gkyo.png",
                   "piece": pieces.Lance},
          "S_BN": {"resource": ":/Ichiji/resources/Ichiji/Gkei.png",
                   "piece": pieces.S_Knight},
          "S_BS": {"resource": ":/Ichiji/resources/Ichiji/Ggin.png",
                   "piece": pieces.Silver},
          "S_BG": {"resource": ":/Ichiji/resources/Ichiji/Gkin.png",
                   "piece": pieces.Gold},
          "S_BK": {"resource": ":/Ichiji/resources/Ichiji/Ggyoku.png",
                   "piece": pieces.S_King},
          "S_BB": {"resource": ":/Ichiji/resources/Ichiji/Gkaku.png",
                   "piece": pieces.S_Bishop},
          "S_BR": {"resource": ":/Ichiji/resources/Ichiji/Ghi.png",
                   "piece": pieces.S_Rook},
          "S_WP": {"resource": ":/Ichiji/resources/Ichiji/Sfu.png",
                   "piece": pieces.S_Pawn},
          "S_WL": {"resource": ":/Ichiji/resources/Ichiji/Skyo.png",
                   "piece": pieces.Lance},
          "S_WN": {"resource": ":/Ichiji/resources/Ichiji/Skei.png",
                   "piece": pieces.S_Knight},
          "S_WS": {"resource": ":/Ichiji/resources/Ichiji/Sgin.png",
                   "piece": pieces.Silver},
          "S_WG": {"resource": ":/Ichiji/resources/Ichiji/Skin.png",
                   "piece": pieces.Gold},
          "S_WK": {"resource": ":/Ichiji/resources/Ichiji/Sou.png",
                   "piece": pieces.S_King},
          "S_WB": {"resource": ":/Ichiji/resources/Ichiji/Skaku.png",
                   "piece": pieces.S_Bishop},
          "S_WR": {"resource": ":/Ichiji/resources/Ichiji/Shi.png",
                   "piece": pieces.S_Rook}}