import chessVshogi.src.pieces as pieces

ichiji_prefix = ":/Ichiji/resources/Ichiji/"
hidetchi_prefix = ":/Hidetchi/resources/hidetchi/"
prefix = hidetchi_prefix


def mapper():
    mpr = {
        "C_WP": {"resource": ":/Chess/resources/chess_48/Chess_plt48.png",
                 "piece": pieces.Pawn},
        "C_WR": {"resource": ":/Chess/resources/chess_48/Chess_rlt48.png",
                 "piece": pieces.Rook},
        "C_WN": {"resource": ":/Chess/resources/chess_48/Chess_nlt48.png",
                 "piece": pieces.Knight},
        "C_WB": {"resource": ":/Chess/resources/chess_48/Chess_blt48.png",
                 "piece": pieces.Bishop},
        "C_WQ": {"resource": ":/Chess/resources/chess_48/Chess_qlt48.png",
                 "piece": pieces.Queen},
        "C_WK": {"resource": ":/Chess/resources/chess_48/Chess_klt48.png",
                 "piece": pieces.King},
        "C_BP": {"resource": ":/Chess/resources/chess_48/Chess_pdt48.png",
                 "piece": pieces.Pawn},
        "C_BR": {"resource": ":/Chess/resources/chess_48/Chess_rdt48.png",
                 "piece": pieces.Rook},
        "C_BN": {"resource": ":/Chess/resources/chess_48/Chess_ndt48.png",
                 "piece": pieces.Knight},
        "C_BB": {"resource": ":/Chess/resources/chess_48/Chess_bdt48.png",
                 "piece": pieces.Bishop},
        "C_BQ": {"resource": ":/Chess/resources/chess_48/Chess_qdt48.png",
                 "piece": pieces.Queen},
        "C_BK": {"resource": ":/Chess/resources/chess_48/Chess_kdt48.png",
                 "piece": pieces.King},
        "S_BP": {"resource": prefix + "Gfu.png",
                 "piece": pieces.SPawn},
        "S_BL": {"resource": prefix + "Gkyo.png",
                 "piece": pieces.Lance},
        "S_BN": {"resource": prefix + "Gkei.png",
                 "piece": pieces.SKnight},
        "S_BS": {"resource": prefix + "Ggin.png",
                 "piece": pieces.Silver},
        "S_BG": {"resource": prefix + "Gkin.png",
                 "piece": pieces.Gold},
        "S_BK": {"resource": prefix + "Ggyoku.png",
                 "piece": pieces.S_King},
        "S_BB": {"resource": prefix + "Gkaku.png",
                 "piece": pieces.SBishop},
        "S_BR": {"resource": prefix + "Ghi.png",
                 "piece": pieces.SRook},
        "S_WP": {"resource": prefix + "Sfu.png",
                 "piece": pieces.SPawn},
        "S_WL": {"resource": prefix + "Skyo.png",
                 "piece": pieces.Lance},
        "S_WN": {"resource": prefix + "Skei.png",
                 "piece": pieces.SKnight},
        "S_WS": {"resource": prefix + "Sgin.png",
                 "piece": pieces.Silver},
        "S_WG": {"resource": prefix + "Skin.png",
                 "piece": pieces.Gold},
        "S_WK": {"resource": prefix + "Sou.png",
                 "piece": pieces.S_King},
        "S_WB": {"resource": prefix + "Skaku.png",
                 "piece": pieces.SBishop},
        "S_WR": {"resource": prefix + "Shi.png",
                 "piece": pieces.SRook},
        "C_WPR": {"resource": ":/Chess/resources/chess_48/Chess_rlt48.png",
                  "piece": pieces.Pawn},
        "C_WPN": {"resource": ":/Chess/resources/chess_48/Chess_nlt48.png",
                  "piece": pieces.Pawn},
        "C_WPB": {"resource": ":/Chess/resources/chess_48/Chess_blt48.png",
                  "piece": pieces.Pawn},
        "C_WPQ": {"resource": ":/Chess/resources/chess_48/Chess_qlt48.png",
                  "piece": pieces.Pawn},
        "S_WPP": {"resource": prefix + "Sto.png",
                  "piece": pieces.PromotedSPawn},
        "S_WLP": {"resource": prefix + "Snkyo.png",
                  "piece": pieces.PromotedLance},
        "S_WNP": {"resource": prefix + "Snkei.png",
                  "piece": pieces.PromotedSKnight},
        "S_WSP": {"resource": prefix + "Sngin.png",
                  "piece": pieces.PromotedSilver},
        "S_WRP": {"resource": prefix + "Sryu.png",
                  "piece": pieces.PromotedSRook},
        "S_WBP": {"resource": prefix + "Suma.png",
                  "piece": pieces.PromotedSBishop},
        "C_BPR": {"resource": ":/Chess/resources/chess_48/Chess_rdt48.png",
                  "piece": pieces.Pawn},
        "C_BPN": {"resource": ":/Chess/resources/chess_48/Chess_ndt48.png",
                  "piece": pieces.Pawn},
        "C_BPB": {"resource": ":/Chess/resources/chess_48/Chess_bdt48.png",
                  "piece": pieces.Pawn},
        "C_BPQ": {"resource": ":/Chess/resources/chess_48/Chess_qdt48.png",
                  "piece": pieces.Pawn},
        "S_BPP": {"resource": prefix + "Gto.png",
                  "piece": pieces.PromotedSPawn},
        "S_BLP": {"resource": prefix + "Gnkyo.png",
                  "piece": pieces.PromotedLance},
        "S_BNP": {"resource": prefix + "Gnkei.png",
                  "piece": pieces.PromotedSKnight},
        "S_BSP": {"resource": prefix + "Gngin.png",
                  "piece": pieces.PromotedSilver},
        "S_BRP": {"resource": prefix + "Gryu.png",
                  "piece": pieces.PromotedSRook},
        "S_BBP": {"resource": prefix + "Guma.png",
                  "piece": pieces.PromotedSBishop},
    }
    return mpr